### PR TITLE
I hope the changes make some sense. 

### PR DESCRIPTION
**Pull request by soulwax**
Review them beforehand, it works for me.

### CODE REVIEW

**Comment by 0-don** [comment]
@soulwax can you please unblock me in discord

**Comment by soulwax** [comment]
Done.

**Comment by 0-don** [comment]
@soulwax  please write me something I cant find you

**Comment by soulwax** [comment]
can't, we don't share a server

**Comment by soulwax** [comment]
So, any questions regarding the changes here?

**Comment by 0-don** [comment]
I will pull the changes when I have time leave it open until

**Pull request closed without merging**
